name: deploy
run-name: CI/CD
on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - run: pwd
      # - run: ls -l
      # - run: chmod +x ./docker-compose-build.yml
      - name: Build Docker Image udagram-api-feed
        run: docker build -t udagram-api-feed ./udagram-api-feed

      - name: Build Docker Image udagram-api-user
        run: docker build -t udagram-api-user ./udagram-api-user

      - name: Build Docker Image udagram-frontend
        run: docker build -t udagram-frontend ./udagram-frontend

      - name: Build Docker Image udagram-reverseproxy
        run: docker build -t udagram-reverseproxy ./udagram-reverseproxy

      - name: Push Docker Image
        run: docker-compose -f docker-compose-build.yml push
