name: deploy
run-name: CI/CD
on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image udagram-api-feed
        run: docker build -t udagram-api-feed ./udagram-api-feed

      - name: Tagging Image udagram-api-feed
        run: docker tag udagram-api-feed alan317/udagram-api-feed:lastest

      - name: Build Docker Image udagram-api-user
        run: docker build -t udagram-api-user ./udagram-api-user

      - name: Tagging Image udagram-api-user
        run: docker tag udagram-api-user alan317/udagram-api-user:lastest

      - name: Build Docker Image udagram-frontend
        run: docker build -t udagram-frontend ./udagram-frontend

      - name: Tagging Image udagram-frontend
        run: docker tag udagram-frontend alan317/udagram-frontend:lastest

      - name: Build Docker Image udagram-reverseproxy
        run: docker build -t udagram-reverseproxy ./udagram-reverseproxy

      - name: Tagging Image udagram-reverseproxy
        run: docker tag udagram-reverseproxy alan317/udagram-reverseproxy:lastest

      - name: Push Docker Image udagram-api-feed
        run: docker push alan317/udagram-api-feed:lastest

      - name: Push Docker Image udagram-api-user
        run: docker push alan317/udagram-api-user:lastest

      - name: Push Docker Image udagram-frontend
        run: docker push alan317/udagram-frontend:lastest

      - name: Push Docker Image udagram-reverseproxy
        run: docker push alan317/udagram-reverseproxy:lastest
