name: deploy
run-name: CI/CD
on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: echo "${GITHUB_WORKSPACE}"
        working-directory: ..
        run: docker-compose -f docker-compose-build.yml build

      - name: Push Docker Image
        working-directory: ..
        run: docker-compose -f docker-compose-build.yml push
