name: deploy
run-name: CI/CD
on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t udagram-api-feed ./udagram-api-feed
          & docker build -t udagram-api-user ./udagram-api-user
          & docker build -t udagram-frontend ./udagram-frontend
          & docker build -t udagram-reverseproxy ./udagram-reverseproxy

      - name: Tagging
        run: |
          docker tag udagram-api-feed alan317/udagram-api-feed:lastest
          & docker tag udagram-api-user alan317/udagram-api-user:lastest
          & docker tag udagram-frontend alan317/udagram-frontend:lastest
          & docker tag udagram-reverseproxy alan317/udagram-reverseproxy:lastest

      - name: Push Docker Image
        run: |
          docker push alan317/udagram-api-feed:lastest
          & docker push alan317/udagram-api-user:lastest
          & docker push alan317/udagram-frontend:lastest
          & docker push alan317/udagram-reverseproxy:lastest
