name: deploy
run-name: CI/CD
on:
  push:
    branches: [main]

env:
  USERNAME: ${{ secrets.DOCKER_USER }}
  PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Log credential
        run: |
          echo $USERNAME >> secrets.txt
          echo $PASSWORD >> secrets.txt

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: $USERNAME
          password: $PASSWORD

      - name: Build Docker Image
        run: docker-compose -f docker-compose-build.yml

      - name: Push Docker Image
        run: docker-compose -f docker-compose-build.yml push
